services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8501:8501
    depends_on:
      - api
    networks:
      - rethread-net

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000
    networks:
      - rethread-net

  db:
    env_file:
      - api/.env
    image: mysql:9
    container_name: mysql_db
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306
    networks:
      - rethread-net

networks:
  rethread-net:
